/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressReverseProperties } from './address-reverse-properties';
import { GeometryPoint } from './geometry-point';


export interface AddressReverse { 
    type?: string;
    properties?: AddressReverseProperties;
    geometry?: GeometryPoint;
}

