/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressReverseProperties { 
    /**
     * Libellé complet de l\'adresse
     */
    label?: string;
    id?: string;
    /**
     * Code postal
     */
    postcode?: string;
    /**
     * Commune de l\'adresse
     */
    city?: string;
    /**
     * Arrondissement de l\'adresse
     */
    district?: string;
    /**
     * Rue de l\'adresse
     */
    street?: string;
    housenumber?: string;
    /**
     * Code INSEE
     */
    citycode?: string;
    /**
     * Longitude de l\'adresse
     */
    x?: number;
    /**
     * Latitude de l\'adresse
     */
    y?: number;
    score?: number;
    _score?: number;
    name?: string;
    type?: AddressReversePropertiesTypeEnum;
    /**
     * Rétro-compatibilité
     */
    _type?: AddressReversePropertiesTypeEnum;
    context?: string;
    importance?: number;
    distance?: number;
}
export enum AddressReversePropertiesTypeEnum {
    HOUSENUMBER = 'housenumber',
    STREET = 'street',
    LOCALITY = 'locality',
    MUNICIPALITY = 'municipality'
};
export enum AddressReversePropertiesTypeEnum {
    ADDRESS = 'address'
};



