/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AsyncProjectsPost401Response { 
    /**
     * Code d\'erreur (HTTP)
     */
    code?: number;
    /**
     * Message d\'erreur
     */
    message?: string;
}

