/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeocodeProcessing { 
    step?: string;
    validationProgress?: object;
    validationError?: string;
    geocodingProgress?: object;
    geocodingError?: string;
    globalError?: string;
    startedAt?: string;
    finishedAt?: string;
    heartbeat?: string;
}

