/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ParcelProperties } from './parcel-properties';
import { Parcel } from './parcel';
import { Poi } from './poi';
import { GeometryPoint } from './geometry-point';


/**
 * @type GeocodeResponse
 * @export
 */
export type GeocodeResponse = Address | Parcel | Poi;

