/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParcelReverseProperties } from './parcel-reverse-properties';
import { PoiReverse } from './poi-reverse';
import { ParcelReverse } from './parcel-reverse';
import { AddressReverse } from './address-reverse';
import { GeometryPoint } from './geometry-point';


/**
 * @type GeocodeReverseResponse
 * @export
 */
export type GeocodeReverseResponse = AddressReverse | ParcelReverse | PoiReverse;

