/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeometryMultiPolygon { 
    type?: GeometryMultiPolygonTypeEnum;
    coordinates?: Array<number>;
}
export enum GeometryMultiPolygonTypeEnum {
    MULTI_POLYGON = 'MultiPolygon'
};



