/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryType } from './geometry-type';


export interface Geometry { 
    type?: GeometryType;
    coordinates?: Array<number>;
}



