/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetcapabilitiesIndexesInnerFieldsInner } from './getcapabilities-indexes-inner-fields-inner';


export interface GetcapabilitiesIndexesInner { 
    id?: string;
    description?: string;
    fields?: Array<GetcapabilitiesIndexesInnerFieldsInner>;
}

