/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetcapabilitiesOperationsInnerParametersInnerSchema } from './getcapabilities-operations-inner-parameters-inner-schema';


export interface GetcapabilitiesOperationsInnerParametersInner { 
    name?: string;
    'in'?: string;
    description?: string;
    required?: boolean;
    'default'?: any | null;
    schema?: GetcapabilitiesOperationsInnerParametersInnerSchema;
    example?: string;
}

