/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetcapabilitiesOperationsInnerParametersInner } from './getcapabilities-operations-inner-parameters-inner';


export interface GetcapabilitiesOperationsInner { 
    id?: string;
    description?: string;
    url?: string;
    methods?: Array<GetcapabilitiesOperationsInnerMethodsEnum>;
    parameters?: Array<GetcapabilitiesOperationsInnerParametersInner>;
}
export enum GetcapabilitiesOperationsInnerMethodsEnum {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    DELETE = 'DELETE'
};



