/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetcapabilitiesIndexesInner } from './getcapabilities-indexes-inner';
import { GetcapabilitiesApi } from './getcapabilities-api';
import { GetcapabilitiesOperationsInner } from './getcapabilities-operations-inner';
import { GetcapabilitiesInfo } from './getcapabilities-info';


export interface Getcapabilities { 
    info?: GetcapabilitiesInfo;
    api?: GetcapabilitiesApi;
    operations?: Array<GetcapabilitiesOperationsInner>;
    indexes?: Array<GetcapabilitiesIndexesInner>;
}

