/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HouseNumberInfos { 
    date?: string;
    kind?: Array<HouseNumberInfosKindEnum>;
    source?: string;
}
export enum HouseNumberInfosKindEnum {
    ENTRANCE = 'entrance',
    BUILDING = 'building',
    STAIRCASE = 'staircase',
    UNIT = 'unit',
    PARCEL = 'parcel',
    SEGMENT = 'segment',
    UTILITY = 'utility',
    AREA = 'area',
    POSTAL = 'postal',
    UNKNOWN = 'unknown'
};



