/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryPolygon } from './geometry-polygon';


export interface ParcelReverseProperties { 
    /**
     * Identifiant de la parcelle
     */
    id?: string;
    /**
     * Code du département
     */
    departmentcode?: string;
    /**
     * Code de la commune
     */
    municipalitycode?: string;
    /**
     * Nom de la commune
     */
    city?: string;
    /**
     * Code de l\'ancienne commune
     */
    oldmunicipalitycode?: string;
    /**
     * Code insee de l\'arrondissement
     */
    districtcode?: string;
    /**
     * Section cadastrale
     */
    section?: string;
    /**
     * Numéro cadastral
     */
    number?: string;
    /**
     * Feuille cadastrale
     */
    sheet?: string;
    truegeometry?: GeometryPolygon;
    _score?: number;
    _type?: ParcelReversePropertiesTypeEnum;
    distance?: number;
}
export enum ParcelReversePropertiesTypeEnum {
    PARCEL = 'parcel'
};



