/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PipelineGeocodeOptions { 
    /**
     * Opération demandée
     */
    operation?: PipelineGeocodeOptionsOperationEnum;
    /**
     * Index à utiliser pour le géocodage
     */
    indexes?: Array<PipelineGeocodeOptionsIndexesEnum>;
    /**
     * Liste des colonnes du fichier CSV à utiliser pour le géocodage. Celles-ci seront concaténées pour former le critère de recherche texte.  Si le paramètre n\'est pas fourni toutes les colonnes seront concaténées, ce qui est rarement souhaitable. 
     */
    columns?: Array<string>;
    /**
     * Colonne contenant le type d’objet accepté pour le géocodage de la ligne (address)
     */
    type?: string;
    /**
     * Colonne contenant le code INSEE de la commune à utiliser comme filtre (address, poi)
     */
    citycode?: string;
    /**
     * Colonne contenant le code postal à utiliser comme filtre (address, poi)
     */
    postcode?: string;
    /**
     * Colonne contenant la catégorie de POI à utiliser comme filtre (poi)
     */
    category?: string;
    /**
     * Colonne contenant la longitude du point de recherche
     */
    lon?: string;
    /**
     * Colonne contenant la latitude du point de recherche
     */
    lat?: string;
    /**
     * Colonne contenant le code département à utiliser comme filtre (parcel)
     */
    departmentcode?: string;
    /**
     * Colonne contenant le code commune  à utiliser comme filtre (parcel)
     */
    municipalitycode?: string;
    /**
     * Colonne contenant l\'ancien code commune à utiliser comme filtre (parcel)
     */
    oldmunicipalitycode?: string;
    /**
     * Colonne contenant le code d\'arrondissement à utiliser comme filtre (parcel)
     */
    districtcode?: string;
    /**
     * Colonne contenant le numéro de section à utiliser comme filtre (parcel)
     */
    section?: string;
    /**
     * Colonne contenant le numéro de feuille à utiliser comme filtre (parcel)
     */
    sheet?: string;
    /**
     * Colonne contenant le numéro de parcelle à utiliser comme filtre (parcel)
     */
    number?: string;
    /**
     * Liste des colonnes de type résultat à conserver dans le fichier de sortie.  Par défaut toutes les colonnes disponibles sont retournées. 
     */
    result_columns?: Array<string>;
}
export enum PipelineGeocodeOptionsOperationEnum {
    SEARCH = 'search',
    REVERSE = 'reverse'
};
export enum PipelineGeocodeOptionsIndexesEnum {
    ADDRESS = 'address',
    POI = 'poi',
    PARCEL = 'parcel'
};



