/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PipelineGeocodeOptions } from './pipeline-geocode-options';


export interface Pipeline { 
    geocodeOptions?: PipelineGeocodeOptions;
    outputFormat?: PipelineOutputFormatEnum;
}
export enum PipelineOutputFormatEnum {
    CSV = 'csv',
    GEOJSON = 'geojson'
};



