/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Geometry } from './geometry';


export interface PoiReverseProperties { 
    /**
     * Libellé du toponyme
     */
    toponym?: string;
    postcode?: Array<string>;
    citycode?: Array<string>;
    city?: Array<string>;
    category?: Array<string>;
    extrafields?: object;
    truegeometry?: Geometry;
    _score?: number;
    _type?: PoiReversePropertiesTypeEnum;
    distance?: number;
}
export enum PoiReversePropertiesTypeEnum {
    POI = 'poi'
};



