/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectParams } from './project-params';
import { GeocodeProcessing } from './geocode-processing';
import { Pipeline } from './pipeline';


export interface Project { 
    id?: string;
    status?: ProjectStatusEnum;
    createdAt?: string;
    updatedAt?: string;
    params?: ProjectParams;
    pipeline?: Pipeline;
    inputFile?: object;
    outputFile?: object;
    processing?: GeocodeProcessing;
    /**
     * Jeton permettant d\'interéagir avec le projet. N\'est retourné que lors de la création.
     */
    token?: string;
}
export enum ProjectStatusEnum {
    IDLE = 'idle',
    WAITING = 'waiting',
    PROCESSING = 'processing',
    FAILED = 'failed',
    COMPLETED = 'completed'
};



