/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectParams { 
    maxInputFileSize?: ProjectParamsMaxInputFileSizeEnum;
    concurrency?: ProjectParamsConcurrencyEnum;
}
export enum ProjectParamsMaxInputFileSizeEnum {
    _50_MB = '50MB',
    _100_MB = '100MB',
    _200_MB = '200MB',
    _500_MB = '500MB',
    _1_GB = '1GB'
};
export enum ProjectParamsConcurrencyEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_4 = 4
};



