/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeocodeResponse } from './geocode-response';


export interface Search200Response { 
    type?: string;
    features?: Array<GeocodeResponse>;
}

