/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { SearchCsv400Response } from '../model/search-csv400-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class BatchService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Géocodage inversé en masse d’un fichier CSV
     * Géocodage inversé en masse d’un fichier CSV. Les paramètres de la requête permettent de spécifier les colonnes à utiliser pour le géocodage, les index à utiliser, les filtres à appliquer et les colonnes à conserver dans le fichier CSV de sortie.  Le fichier soumis doit faire une taille maximale de 50 Mo. 
     * @param data Fichier CSV contenant les données à géocoder
     * @param indexes Liste des index à utiliser pour le géocodage (parmi address, poi, parcel)
     * @param type Colonne contenant le type d’objet accepté pour le géocodage de la ligne (address)
     * @param citycode Colonne contenant le code INSEE de la commune à utiliser comme filtre (address, poi)
     * @param postcode Colonne contenant le code postal à utiliser comme filtre (address, poi)
     * @param category Colonne contenant la catégorie de POI à utiliser comme filtre (poi)
     * @param lon Colonne contenant la longitude du point de recherche
     * @param lat Colonne contenant la latitude du point de recherche
     * @param departmentcode Colonne contenant le code département à utiliser comme filtre (parcel)
     * @param municipalitycode Colonne contenant le code commune  à utiliser comme filtre (parcel)
     * @param oldmunicipalitycode Colonne contenant l\\\&#39;ancien code commune à utiliser comme filtre (parcel)
     * @param districtcode Colonne contenant le code d\\\&#39;arrondissement à utiliser comme filtre (parcel)
     * @param section Colonne contenant le numéro de section à utiliser comme filtre (parcel)
     * @param sheet Colonne contenant le numéro de feuille à utiliser comme filtre (parcel)
     * @param number Colonne contenant le numéro de parcelle à utiliser comme filtre (parcel)
     * @param resultColumns Liste des colonnes de type résultat à conserver dans le fichier CSV de sortie.  Par défaut toutes les colonnes disponibles sont retournées. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Blob>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Blob>>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Blob>>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling reverseCsv.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/csv',
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (data !== undefined) {
            localVarFormParams = localVarFormParams.append('data', <any>data) as any || localVarFormParams;
        }
        if (indexes) {
            indexes.forEach((element) => {
                localVarFormParams = localVarFormParams.append('indexes', <any>element) as any || localVarFormParams;
            })
        }
        if (type !== undefined) {
            localVarFormParams = localVarFormParams.append('type', <any>type) as any || localVarFormParams;
        }
        if (citycode !== undefined) {
            localVarFormParams = localVarFormParams.append('citycode', <any>citycode) as any || localVarFormParams;
        }
        if (postcode !== undefined) {
            localVarFormParams = localVarFormParams.append('postcode', <any>postcode) as any || localVarFormParams;
        }
        if (category !== undefined) {
            localVarFormParams = localVarFormParams.append('category', <any>category) as any || localVarFormParams;
        }
        if (lon !== undefined) {
            localVarFormParams = localVarFormParams.append('lon', <any>lon) as any || localVarFormParams;
        }
        if (lat !== undefined) {
            localVarFormParams = localVarFormParams.append('lat', <any>lat) as any || localVarFormParams;
        }
        if (departmentcode !== undefined) {
            localVarFormParams = localVarFormParams.append('departmentcode', <any>departmentcode) as any || localVarFormParams;
        }
        if (municipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('municipalitycode', <any>municipalitycode) as any || localVarFormParams;
        }
        if (oldmunicipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('oldmunicipalitycode', <any>oldmunicipalitycode) as any || localVarFormParams;
        }
        if (districtcode !== undefined) {
            localVarFormParams = localVarFormParams.append('districtcode', <any>districtcode) as any || localVarFormParams;
        }
        if (section !== undefined) {
            localVarFormParams = localVarFormParams.append('section', <any>section) as any || localVarFormParams;
        }
        if (sheet !== undefined) {
            localVarFormParams = localVarFormParams.append('sheet', <any>sheet) as any || localVarFormParams;
        }
        if (number !== undefined) {
            localVarFormParams = localVarFormParams.append('number', <any>number) as any || localVarFormParams;
        }
        if (resultColumns) {
            resultColumns.forEach((element) => {
                localVarFormParams = localVarFormParams.append('result_columns', <any>element) as any || localVarFormParams;
            })
        }

        let localVarPath = `/reverse/csv`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: "blob",
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Géocodage direct en masse d’un fichier CSV
     * Géocodage direct en masse d’un fichier CSV. Les paramètres de la requête permettent de spécifier les colonnes à utiliser pour le géocodage, les index à utiliser, les filtres à appliquer et les colonnes à conserver dans le fichier CSV de sortie.  Le fichier soumis doit faire une taille maximale de 50 Mo. 
     * @param data Fichier CSV contenant les lignes à géocoder
     * @param columns Liste des colonnes du fichier CSV à utiliser pour le géocodage. Celles-ci seront concaténées pour former le critère de recherche texte.  Si le paramètre n\\\&#39;est pas fourni toutes les colonnes seront concaténées, ce qui est rarement souhaitable. 
     * @param indexes Liste des index à utiliser pour le géocodage (parmi address, poi, parcel)
     * @param type Colonne contenant le type d’objet accepté pour le géocodage de la ligne (address)
     * @param citycode Colonne contenant le code INSEE de la commune à utiliser comme filtre (address, poi)
     * @param postcode Colonne contenant le code postal à utiliser comme filtre (address, poi)
     * @param category Colonne contenant la catégorie de POI à utiliser comme filtre (poi)
     * @param lon Colonne contenant la longitude du point de recherche
     * @param lat Colonne contenant la latitude du point de recherche
     * @param departmentcode Colonne contenant le code département à utiliser comme filtre (parcel)
     * @param municipalitycode Colonne contenant le code commune  à utiliser comme filtre (parcel)
     * @param oldmunicipalitycode Colonne contenant l\\\&#39;ancien code commune à utiliser comme filtre (parcel)
     * @param districtcode Colonne contenant le code d\\\&#39;arrondissement à utiliser comme filtre (parcel)
     * @param section Colonne contenant le numéro de section à utiliser comme filtre (parcel)
     * @param sheet Colonne contenant le numéro de feuille à utiliser comme filtre (parcel)
     * @param number Colonne contenant le numéro de parcelle à utiliser comme filtre (parcel)
     * @param resultColumns Liste des colonnes de type résultat à conserver dans le fichier CSV de sortie.  Par défaut toutes les colonnes disponibles sont retournées. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchCsv(data: Blob, columns?: Array<string>, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Blob>;
    public searchCsv(data: Blob, columns?: Array<string>, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Blob>>;
    public searchCsv(data: Blob, columns?: Array<string>, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Blob>>;
    public searchCsv(data: Blob, columns?: Array<string>, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling searchCsv.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/csv',
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (data !== undefined) {
            localVarFormParams = localVarFormParams.append('data', <any>data) as any || localVarFormParams;
        }
        if (columns) {
            columns.forEach((element) => {
                localVarFormParams = localVarFormParams.append('columns', <any>element) as any || localVarFormParams;
            })
        }
        if (indexes) {
            indexes.forEach((element) => {
                localVarFormParams = localVarFormParams.append('indexes', <any>element) as any || localVarFormParams;
            })
        }
        if (type !== undefined) {
            localVarFormParams = localVarFormParams.append('type', <any>type) as any || localVarFormParams;
        }
        if (citycode !== undefined) {
            localVarFormParams = localVarFormParams.append('citycode', <any>citycode) as any || localVarFormParams;
        }
        if (postcode !== undefined) {
            localVarFormParams = localVarFormParams.append('postcode', <any>postcode) as any || localVarFormParams;
        }
        if (category !== undefined) {
            localVarFormParams = localVarFormParams.append('category', <any>category) as any || localVarFormParams;
        }
        if (lon !== undefined) {
            localVarFormParams = localVarFormParams.append('lon', <any>lon) as any || localVarFormParams;
        }
        if (lat !== undefined) {
            localVarFormParams = localVarFormParams.append('lat', <any>lat) as any || localVarFormParams;
        }
        if (departmentcode !== undefined) {
            localVarFormParams = localVarFormParams.append('departmentcode', <any>departmentcode) as any || localVarFormParams;
        }
        if (municipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('municipalitycode', <any>municipalitycode) as any || localVarFormParams;
        }
        if (oldmunicipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('oldmunicipalitycode', <any>oldmunicipalitycode) as any || localVarFormParams;
        }
        if (districtcode !== undefined) {
            localVarFormParams = localVarFormParams.append('districtcode', <any>districtcode) as any || localVarFormParams;
        }
        if (section !== undefined) {
            localVarFormParams = localVarFormParams.append('section', <any>section) as any || localVarFormParams;
        }
        if (sheet !== undefined) {
            localVarFormParams = localVarFormParams.append('sheet', <any>sheet) as any || localVarFormParams;
        }
        if (number !== undefined) {
            localVarFormParams = localVarFormParams.append('number', <any>number) as any || localVarFormParams;
        }
        if (resultColumns) {
            resultColumns.forEach((element) => {
                localVarFormParams = localVarFormParams.append('result_columns', <any>element) as any || localVarFormParams;
            })
        }

        let localVarPath = `/search/csv`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: "blob",
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
