/**
 * Service de géocodage
 *
 * Contact: contact.geoservices@ign.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Index } from '../model/index';
// @ts-ignore
import { Reverse200Response } from '../model/reverse200-response';
// @ts-ignore
import { SearchCsv400Response } from '../model/search-csv400-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ReverseService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Recherche par géocodage inverse
     * @param searchgeom Géométrie de recherche. La géométrie est réalisé par intersection géométrique. Si ce paramètre est utilisé seul, c\&#39;\&#39;est que l\&#39;\&#39;on souhaite une recherche sans ordonnancement des résultats (tous les objets intersectant la géométrie de recherche ont un score de 1). Si on veut ordonner les résultats, on peut alors utiliser les paramètres lon et lat pour préciser un point d\&#39;\&#39;ordonnancement. Ce paramètre n\&#39;\&#39;est pas obligatoire pour des raisons de rétro-compatibilité. Si searchgeom n\&#39;\&#39;est pas utilisé alors les paramètres lon et lat doivent l\&#39;\&#39;être et on parle de point de recherche. Lorsque la recherche est réalisée par intersection géométrique. Les types géométrique autorisés sont :  - Point  - LineString  - Polygon  - Circle Exemple de géométrie de type Circle : { &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;\&quot;type\&quot;: \&quot;Circle\&quot;, &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;\&quot;coordinates\&quot;: [2.294469, 48.858244], &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;\&quot;radius\&quot;: 100 } Pour l\&#39;\&#39;index &lt;b&gt;address&lt;/b&gt;, seules les géométries de type \&#39;\&#39;Polygon\&#39;\&#39; et \&#39;\&#39;Circle\&#39;\&#39; sont autorisées. Le plus grand côté du rectangle d’emprise de la géométrie ne doit pas excéder 1000 mètres. 
     * @param lon Si searchgeom est utilisé, il s\&#39;agit de la longitude du point d\&#39;ordonnancement. C\&#39;est le point à partir duquel est calculée la distance, puis le score permettant l\&#39;ordonnancement des résultats. Dans un soucis de rétro-compatibilité, si searchgeom n\&#39;est pas utilisé, il s\&#39;agit de la longitude du point de recherche. À partir de ce point, un cercle est créé pour effectuer la recherche. En plus, ce sera aussi la longitude du point d\&#39;ordonnancement. 
     * @param lat Si searchgeom est utilisé, il s\&#39;agit de la latitude  du point d\&#39;ordonnancement. C\&#39;est le point à partir duquel est calculée la distance, puis le score permettant l\&#39;ordonnancement des résultats. Dans un soucis de rétro-compatibilité, si searchgeom n\&#39;est pas utilisé, il s\&#39;agit de la latitude du point de recherche. À partir de ce point, un cercle est créé pour effectuer la recherche. En plus, ce sera aussi la latitude du point d\&#39;ordonnancement. 
     * @param index index de recherche : - &lt;b&gt;address&lt;/b&gt; pour la recherche par adresse - &lt;b&gt;parcel&lt;/b&gt; pour la recherche par parcelle cadastrale - &lt;b&gt;poi&lt;/b&gt; pour la recherche par lieu et unité administrative  Il est possible de spécifier plusieurs indexes séparés par une virgule.  Exemples: - /search?index&#x3D;parcel - /search?index&#x3D;poi,address 
     * @param limit Nombre maximum de résultats retournés. La valeur ne peut pas dépasser 50. Dans le cas où returntruegeometry est activé, la valeur est automatiquement ramenée à 20. 
     * @param returntruegeometry indique si la vraie géométrie doit être retournée
     * @param postcode Filtre pour les index address et poi. Il permet de filtrer les résultats par code postal.
     * @param citycode Filtre pour les index address et poi. Il permet de filtrer les résultats par code INSEE.
     * @param type Filtre pour l\&#39;index address. Il permet de filtrer par type de données adresse : numéro de maison, rue, commune, ...
     * @param city Filtre pour les index address et parcel. Il permet de filtrer par nom de commune.
     * @param category Filtre pour l\&#39;index poi. Il permet de filtrer par catégorie de poi. Les valeurs possibles sont listées dans le getCapabilities du service de géocodage. 
     * @param departmentcode Filtre pour l\&#39;index parcel. Il permet de filtrer par code de département.
     * @param municipalitycode Filtre pour l\&#39;index parcel. Il permet de filtrer par code de commune.
     * @param oldmunicipalitycode Filtre pour l\&#39;index parcel. Il permet de filtrer par code d\&#39;ancienne commune.
     * @param districtcode Filtre pour l\&#39;index parcel. Il permet de filtrer par code d\&#39;arrondissement.
     * @param section Filtre pour l\&#39;index parcel. Il permet de filtrer par section.
     * @param number Filtre pour l\&#39;index parcel. Il permet de filtrer par numéro.
     * @param sheet Filtre pour l\&#39;index parcel. Il permet de filtrer par feuille.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reverse(searchgeom?: string, lon?: number, lat?: number, index?: Index, limit?: number, returntruegeometry?: boolean, postcode?: string, citycode?: string, type?: 'housenumber' | 'street' | 'locality' | 'municipality', city?: string, category?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, number?: string, sheet?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Reverse200Response>;
    public reverse(searchgeom?: string, lon?: number, lat?: number, index?: Index, limit?: number, returntruegeometry?: boolean, postcode?: string, citycode?: string, type?: 'housenumber' | 'street' | 'locality' | 'municipality', city?: string, category?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, number?: string, sheet?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Reverse200Response>>;
    public reverse(searchgeom?: string, lon?: number, lat?: number, index?: Index, limit?: number, returntruegeometry?: boolean, postcode?: string, citycode?: string, type?: 'housenumber' | 'street' | 'locality' | 'municipality', city?: string, category?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, number?: string, sheet?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Reverse200Response>>;
    public reverse(searchgeom?: string, lon?: number, lat?: number, index?: Index, limit?: number, returntruegeometry?: boolean, postcode?: string, citycode?: string, type?: 'housenumber' | 'street' | 'locality' | 'municipality', city?: string, category?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, number?: string, sheet?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>searchgeom, 'searchgeom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>lon, 'lon');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>lat, 'lat');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>index, 'index');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>returntruegeometry, 'returntruegeometry');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>postcode, 'postcode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>citycode, 'citycode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>type, 'type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>city, 'city');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>category, 'category');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>departmentcode, 'departmentcode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>municipalitycode, 'municipalitycode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>oldmunicipalitycode, 'oldmunicipalitycode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>districtcode, 'districtcode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>section, 'section');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>number, 'number');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sheet, 'sheet');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reverse`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Reverse200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Géocodage inversé en masse d’un fichier CSV
     * Géocodage inversé en masse d’un fichier CSV. Les paramètres de la requête permettent de spécifier les colonnes à utiliser pour le géocodage, les index à utiliser, les filtres à appliquer et les colonnes à conserver dans le fichier CSV de sortie.  Le fichier soumis doit faire une taille maximale de 50 Mo. 
     * @param data Fichier CSV contenant les données à géocoder
     * @param indexes Liste des index à utiliser pour le géocodage (parmi address, poi, parcel)
     * @param type Colonne contenant le type d’objet accepté pour le géocodage de la ligne (address)
     * @param citycode Colonne contenant le code INSEE de la commune à utiliser comme filtre (address, poi)
     * @param postcode Colonne contenant le code postal à utiliser comme filtre (address, poi)
     * @param category Colonne contenant la catégorie de POI à utiliser comme filtre (poi)
     * @param lon Colonne contenant la longitude du point de recherche
     * @param lat Colonne contenant la latitude du point de recherche
     * @param departmentcode Colonne contenant le code département à utiliser comme filtre (parcel)
     * @param municipalitycode Colonne contenant le code commune  à utiliser comme filtre (parcel)
     * @param oldmunicipalitycode Colonne contenant l\\\&#39;ancien code commune à utiliser comme filtre (parcel)
     * @param districtcode Colonne contenant le code d\\\&#39;arrondissement à utiliser comme filtre (parcel)
     * @param section Colonne contenant le numéro de section à utiliser comme filtre (parcel)
     * @param sheet Colonne contenant le numéro de feuille à utiliser comme filtre (parcel)
     * @param number Colonne contenant le numéro de parcelle à utiliser comme filtre (parcel)
     * @param resultColumns Liste des colonnes de type résultat à conserver dans le fichier CSV de sortie.  Par défaut toutes les colonnes disponibles sont retournées. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Blob>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Blob>>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Blob>>;
    public reverseCsv(data: Blob, indexes?: Array<string>, type?: string, citycode?: string, postcode?: string, category?: string, lon?: string, lat?: string, departmentcode?: string, municipalitycode?: string, oldmunicipalitycode?: string, districtcode?: string, section?: string, sheet?: string, number?: string, resultColumns?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/csv' | 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling reverseCsv.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/csv',
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (data !== undefined) {
            localVarFormParams = localVarFormParams.append('data', <any>data) as any || localVarFormParams;
        }
        if (indexes) {
            indexes.forEach((element) => {
                localVarFormParams = localVarFormParams.append('indexes', <any>element) as any || localVarFormParams;
            })
        }
        if (type !== undefined) {
            localVarFormParams = localVarFormParams.append('type', <any>type) as any || localVarFormParams;
        }
        if (citycode !== undefined) {
            localVarFormParams = localVarFormParams.append('citycode', <any>citycode) as any || localVarFormParams;
        }
        if (postcode !== undefined) {
            localVarFormParams = localVarFormParams.append('postcode', <any>postcode) as any || localVarFormParams;
        }
        if (category !== undefined) {
            localVarFormParams = localVarFormParams.append('category', <any>category) as any || localVarFormParams;
        }
        if (lon !== undefined) {
            localVarFormParams = localVarFormParams.append('lon', <any>lon) as any || localVarFormParams;
        }
        if (lat !== undefined) {
            localVarFormParams = localVarFormParams.append('lat', <any>lat) as any || localVarFormParams;
        }
        if (departmentcode !== undefined) {
            localVarFormParams = localVarFormParams.append('departmentcode', <any>departmentcode) as any || localVarFormParams;
        }
        if (municipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('municipalitycode', <any>municipalitycode) as any || localVarFormParams;
        }
        if (oldmunicipalitycode !== undefined) {
            localVarFormParams = localVarFormParams.append('oldmunicipalitycode', <any>oldmunicipalitycode) as any || localVarFormParams;
        }
        if (districtcode !== undefined) {
            localVarFormParams = localVarFormParams.append('districtcode', <any>districtcode) as any || localVarFormParams;
        }
        if (section !== undefined) {
            localVarFormParams = localVarFormParams.append('section', <any>section) as any || localVarFormParams;
        }
        if (sheet !== undefined) {
            localVarFormParams = localVarFormParams.append('sheet', <any>sheet) as any || localVarFormParams;
        }
        if (number !== undefined) {
            localVarFormParams = localVarFormParams.append('number', <any>number) as any || localVarFormParams;
        }
        if (resultColumns) {
            resultColumns.forEach((element) => {
                localVarFormParams = localVarFormParams.append('result_columns', <any>element) as any || localVarFormParams;
            })
        }

        let localVarPath = `/reverse/csv`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: "blob",
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
